Soft tigger fly scan
DiamondLightSource/p99-bluesky pull request #35
Opened 2024-07-03 16:26 UTC by Relm-Arrowny

#34

2024-07-03 17:01 UTC, Relm-Arrowny commented
This is far from ready but am worry that this is not the right way to go about it, in pacifically the logic of this function:[_fast_scan_1d](https://github.com/DiamondLightSource/p99-bluesky/blob/75176f43e637aa392eec9bb345d9e1f48a76bdc9/src/p99_bluesky/plans/fast_scan.py#L140).  I am wondering if you have time could you have look and make sure I have not missed a better way of doing it.  @DominicOram @callumforrester @stan-dot

2024-07-04 07:56 UTC, stan-dot commented on src/p99_bluesky/plans/fast_scan.py
> +    high_limit = yield from bps.rd(motor.high_limit_travel)
perhaps move this to `p99_bluesky/src/stubs/check_motor_within_limit`?  with the view of moving into dodal later?

2024-07-04 07:56 UTC, stan-dot commented on src/p99_bluesky/plans/fast_scan.py
> +    ):
it's missing the `-> MsgGenerator` I think

2024-07-04 07:56 UTC, stan-dot commented on src/p99_bluesky/plans/fast_scan.py
> +                yield from bps.mv(step_motor, step_start + step_size * step_counter)
nit: extract the target location from the move line

2024-07-04 07:56 UTC, stan-dot commented on src/p99_bluesky/plans/stxm.py
> +    ideal_step_size = 1.0 / ((num_data_point / (scan_range * step_range)) ** 0.5)
should: add a comment why this is the ideal step size

2024-07-04 07:56 UTC, stan-dot commented on src/p99_bluesky/plans/stxm.py
> +    import math
not sure why import mid-function

2024-07-04 07:56 UTC, stan-dot commented on src/p99_bluesky/plans/stxm.py
> +# ):
delete the commented out code

2024-07-04 09:23 UTC, Relm-Arrowny commented
[Flyable motor may be better way of doing this.](https://github.com/bluesky/ophyd-async/pull/425),

2024-07-05 14:00 UTC, stan-dot requested changes

2024-07-05 14:00 UTC, stan-dot commented on tests/test_fast_scan.py
> +#     assert 20 == get_mock_put(sim_motor.y.velocity).call_count
should: delete commented out code

2024-07-08 09:55 UTC, callumforrester commented on pyproject.toml
> +    tests: pytest --cov=p99_bluesky --cov-report term  --cov-report xml:cov.xml {posargs}
It's still there

2024-07-10 08:37 UTC, callumforrester commented
@Relm-Arrowny this may be for a later PR but you should consider starting to use [scanspec](https://github.com/dls-controls/scanspec)

2024-07-12 14:22 UTC, merged